"""T72 identity embedding enrichment.

The active app venv stays lightweight. Real face embeddings are generated by an
external Python interpreter, normally an isolated env that can import
InsightFace/ArcFace dependencies. If that provider is unavailable, this script
fails closed and writes no embedding placeholders.
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path("/Users/a1234/Desktop/案例生成器/case-workbench")
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend import source_images  # noqa: E402

DEFAULT_DB_PATH = ROOT / "case-workbench.db"
DEFAULT_JSON_OUTPUT = ROOT / "tasks" / "t72_identity_embedding_enrichment_report.json"
DEFAULT_MARKDOWN_OUTPUT = ROOT / "tasks" / "t72_identity_embedding_enrichment_report.md"
DEFAULT_WORKER_SCRIPT = ROOT / "backend" / "scripts" / "identity_embedding_worker.py"
UNVERIFIED = "未验证/无法获取"
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".heic"}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _json_load(raw: str | None, default: Any) -> Any:
    try:
        parsed = json.loads(raw or "")
    except (TypeError, ValueError, json.JSONDecodeError):
        return default
    return parsed


def _json_dump(payload: Any) -> str:
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _case_image_files(row: sqlite3.Row) -> list[str]:
    meta = _json_load(row["meta_json"] if "meta_json" in row.keys() else None, {})
    if not isinstance(meta, dict):
        return []
    files = [str(item) for item in meta.get("image_files") or [] if str(item)]
    return [
        item
        for item in source_images.filter_source_image_files(files)
        if Path(item).suffix.lower() in IMAGE_EXTS
    ]


def _skill_index(items: list[Any]) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]]]:
    ordered = [dict(item) for item in items if isinstance(item, dict)]
    index: dict[str, dict[str, Any]] = {}
    for item in ordered:
        for key in (item.get("filename"), item.get("relative_path")):
            if key:
                index[str(key)] = item
                index[Path(str(key)).name] = item
    return ordered, index


def _selected_case_clause(case_ids: set[int] | None) -> tuple[str, list[Any]]:
    if not case_ids:
        return "", []
    placeholders = ",".join("?" * len(case_ids))
    return f" AND id IN ({placeholders})", sorted(case_ids)


def _parse_case_ids(value: str) -> set[int]:
    out: set[int] = set()
    for raw in str(value or "").replace(" ", "").split(","):
        if not raw:
            continue
        try:
            parsed = int(raw)
        except ValueError:
            continue
        if parsed > 0:
            out.add(parsed)
    return out


def _run_worker(
    provider_python: Path | str | None,
    worker_script: Path | str = DEFAULT_WORKER_SCRIPT,
    args: list[str] | None = None,
    *,
    timeout: int = 240,
) -> dict[str, Any]:
    python_path = Path(provider_python or sys.executable).expanduser()
    worker_path = Path(worker_script).expanduser()
    if not python_path.is_file():
        return {
            "status": "unavailable",
            "provider": None,
            "readiness": UNVERIFIED,
            "reason": f"provider python not found: {python_path}",
        }
    if not worker_path.is_file():
        return {
            "status": "unavailable",
            "provider": None,
            "readiness": UNVERIFIED,
            "reason": f"identity worker not found: {worker_path}",
        }
    try:
        result = subprocess.run(
            [str(python_path), str(worker_path), *(args or [])],
            check=False,
            text=True,
            capture_output=True,
            timeout=timeout,
        )
    except Exception as exc:  # noqa: BLE001
        return {
            "status": "unavailable",
            "provider": None,
            "readiness": UNVERIFIED,
            "error_type": type(exc).__name__,
            "reason": str(exc)[:800],
        }
    stdout = (result.stdout or "").strip()
    try:
        payload = json.loads(stdout.splitlines()[-1] if stdout else "{}")
    except (ValueError, json.JSONDecodeError):
        payload = {
            "status": "error",
            "provider": None,
            "error_type": "InvalidWorkerJson",
            "error": stdout[:800],
        }
    if result.returncode != 0 and payload.get("status") not in {"unavailable"}:
        payload.setdefault("status", "error")
        payload.setdefault("returncode", result.returncode)
        payload.setdefault("stderr", (result.stderr or "")[:800])
    return payload


def identity_provider_readiness(
    provider_python: Path | str | None = None,
    worker_script: Path | str = DEFAULT_WORKER_SCRIPT,
) -> dict[str, Any]:
    payload = _run_worker(provider_python, worker_script, ["--probe"], timeout=60)
    status = str(payload.get("status") or "unavailable")
    if status == "available":
        payload["can_generate_embeddings"] = True
        payload["fallback_policy"] = "human_review_required_for_low_confidence"
        return payload
    return {
        **payload,
        "status": "unavailable",
        "can_generate_embeddings": False,
        "readiness": UNVERIFIED,
        "fallback_policy": "human_review_required",
    }


def _embedding_results(
    image_paths: list[Path],
    *,
    provider_python: Path | str | None = None,
    worker_script: Path | str = DEFAULT_WORKER_SCRIPT,
) -> dict[str, dict[str, Any]]:
    payload = _run_worker(
        provider_python,
        worker_script,
        ["--images-json", json.dumps([str(path) for path in image_paths], ensure_ascii=False)],
        timeout=max(240, len(image_paths) * 12),
    )
    out: dict[str, dict[str, Any]] = {}
    if payload.get("status") != "ok":
        return out
    provider = str(payload.get("provider") or "unknown_identity_provider")
    embedding_dim = payload.get("embedding_dim")
    for item in payload.get("items") or []:
        if not isinstance(item, dict):
            continue
        path = str(item.get("path") or "")
        if not path:
            continue
        normalized = dict(item)
        normalized["provider"] = provider
        normalized["embedding_dim"] = embedding_dim
        out[str(Path(path).resolve())] = normalized
    return out


def _merge_identity_result(item: dict[str, Any], result: dict[str, Any], *, generated_at: str) -> tuple[dict[str, Any], bool]:
    if result.get("status") != "embedded" or not isinstance(result.get("embedding"), list):
        return item, False
    embedding: list[float] = []
    for value in result.get("embedding") or []:
        try:
            embedding.append(round(float(value), 6))
        except (TypeError, ValueError):
            return item, False
    if not embedding:
        return item, False
    merged = dict(item)
    merged.update(
        {
            "identity_embedding": embedding,
            "identity_embedding_source": "real_identity_provider",
            "identity_embedding_generated_at": generated_at,
            "identity_provider": result.get("provider") or "unknown_identity_provider",
            "identity_embedding_dim": int(result.get("embedding_dim") or len(embedding)),
            "identity_face_count": int(result.get("face_count") or 0),
            "identity_detection_score": result.get("det_score"),
            "identity_bbox": result.get("bbox"),
        }
    )
    return merged, merged != item


def enrich_identity_embeddings(
    db_path: Path | str,
    *,
    dry_run: bool = True,
    case_ids: set[int] | None = None,
    limit: int | None = None,
    provider_python: Path | str | None = None,
    worker_script: Path | str = DEFAULT_WORKER_SCRIPT,
) -> dict[str, Any]:
    db_path = Path(db_path).expanduser().resolve()
    generated_at = _now()
    readiness = identity_provider_readiness(provider_python, worker_script)
    if not readiness.get("can_generate_embeddings"):
        return {
            "generated_at": generated_at,
            "run_status": "blocked_identity_provider_unavailable",
            "decision": f"{UNVERIFIED}: identity provider 不可用，未写入任何 embedding。",
            "used_mock_data": False,
            "db_path": str(db_path),
            "dry_run": dry_run,
            "summary": {
                "case_count": 0,
                "processed_image_count": 0,
                "identity_embedding_signal_count": 0,
                "status_counts": {"provider_unavailable": 1},
            },
            "readiness": {
                "identity": {
                    "ready": False,
                    "status": UNVERIFIED,
                    "count": 0,
                    "provider": readiness,
                }
            },
            "case_results": [],
        }

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        clause, params = _selected_case_clause(case_ids)
        sql = (
            "SELECT id, abs_path, meta_json, skill_image_metadata_json "
            f"FROM cases WHERE trashed_at IS NULL{clause} ORDER BY id"
        )
        if limit is not None and limit > 0:
            sql += " LIMIT ?"
            params = [*params, int(limit)]
        rows = conn.execute(sql, params).fetchall()

        targets: list[dict[str, Any]] = []
        status_counts: Counter[str] = Counter()
        for row in rows:
            case_id = int(row["id"])
            case_dir = Path(str(row["abs_path"] or ""))
            for filename in _case_image_files(row):
                image_path = (case_dir / filename).resolve()
                if not image_path.is_file():
                    status_counts["missing_file"] += 1
                    continue
                targets.append({"case_id": case_id, "filename": filename, "path": image_path})

        results_by_path = _embedding_results(
            [target["path"] for target in targets],
            provider_python=provider_python,
            worker_script=worker_script,
        )

        updated_case_count = 0
        identity_embedding_signal_count = 0
        case_results: list[dict[str, Any]] = []
        targets_by_case: dict[int, list[dict[str, Any]]] = {}
        for target in targets:
            targets_by_case.setdefault(int(target["case_id"]), []).append(target)

        for row in rows:
            case_id = int(row["id"])
            raw_items = _json_load(row["skill_image_metadata_json"], [])
            if not isinstance(raw_items, list):
                raw_items = []
            ordered, index = _skill_index(raw_items)
            changed = False
            image_results: list[dict[str, Any]] = []
            for target in targets_by_case.get(case_id, []):
                filename = str(target["filename"])
                result = results_by_path.get(str(target["path"].resolve()))
                if not result:
                    status_counts["embedding_unavailable"] += 1
                    image_results.append({"filename": filename, "status": "embedding_unavailable"})
                    continue
                status = str(result.get("status") or "unknown")
                status_counts[status] += 1
                item = index.get(filename) or index.get(Path(filename).name)
                if item is None:
                    item = {"filename": filename, "relative_path": filename}
                    ordered.append(item)
                    index[filename] = item
                    index[Path(filename).name] = item
                merged, did_change = _merge_identity_result(item, result, generated_at=generated_at)
                if did_change:
                    item.clear()
                    item.update(merged)
                    changed = True
                    identity_embedding_signal_count += 1
                image_results.append(
                    {
                        "filename": filename,
                        "status": status,
                        "face_count": result.get("face_count"),
                        "det_score": result.get("det_score"),
                    }
                )
            if changed:
                updated_case_count += 1
                if not dry_run:
                    conn.execute(
                        "UPDATE cases SET skill_image_metadata_json = ? WHERE id = ?",
                        (_json_dump(ordered), case_id),
                    )
            case_results.append(
                {
                    "case_id": case_id,
                    "image_count": len(image_results),
                    "changed": changed,
                    "images": image_results[:12],
                }
            )
        if dry_run:
            conn.rollback()
        else:
            conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    summary = {
        "case_count": len(rows),
        "processed_image_count": len(targets),
        "updated_case_count": updated_case_count,
        "identity_embedding_signal_count": identity_embedding_signal_count,
        "status_counts": dict(sorted(status_counts.items())),
    }
    ready = identity_embedding_signal_count > 0
    return {
        "generated_at": generated_at,
        "run_status": "dry_run_completed" if dry_run else "applied_real_identity_embeddings",
        "decision": (
            "真实 identity embedding 已写入 skill metadata。"
            if ready and not dry_run
            else f"{UNVERIFIED}: identity embedding 未形成真实写回，或当前为 dry-run。"
        ),
        "used_mock_data": False,
        "db_path": str(db_path),
        "dry_run": dry_run,
        "summary": summary,
        "readiness": {
            "identity": {
                "ready": ready,
                "status": "ready" if ready else UNVERIFIED,
                "count": identity_embedding_signal_count,
                "provider": readiness,
            }
        },
        "case_results": case_results[:80],
    }


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_markdown(path: Path, report: dict[str, Any]) -> None:
    summary = report.get("summary") or {}
    identity = ((report.get("readiness") or {}).get("identity") or {})
    provider = identity.get("provider") or {}
    lines = [
        "# T72 Identity Embedding Enrichment Report",
        "",
        f"- run_status: `{report.get('run_status')}`",
        f"- decision: {report.get('decision')}",
        f"- used_mock_data: `{report.get('used_mock_data')}`",
        f"- dry_run: `{report.get('dry_run')}`",
        f"- case_count: {summary.get('case_count')}",
        f"- processed_image_count: {summary.get('processed_image_count')}",
        f"- updated_case_count: {summary.get('updated_case_count')}",
        f"- identity_embedding_signal_count: {summary.get('identity_embedding_signal_count')}",
        f"- identity_ready: `{identity.get('ready')}`",
        f"- identity_status: {identity.get('status')}",
        "",
        "## Provider",
        "",
        f"- status: `{provider.get('status')}`",
        f"- provider: `{provider.get('provider')}`",
        f"- can_generate_embeddings: `{provider.get('can_generate_embeddings')}`",
        f"- fallback_policy: `{provider.get('fallback_policy')}`",
        f"- readiness: {provider.get('readiness') or 'ready'}",
        "",
        "## Status Counts",
        "",
    ]
    for key, value in (summary.get("status_counts") or {}).items():
        lines.append(f"- `{key}`: {value}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Enrich source metadata with real identity embeddings.")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_JSON_OUTPUT)
    parser.add_argument("--markdown-output", type=Path, default=DEFAULT_MARKDOWN_OUTPUT)
    parser.add_argument("--case-ids", default="")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--provider-python", type=Path)
    parser.add_argument("--worker-script", type=Path, default=DEFAULT_WORKER_SCRIPT)
    parser.add_argument("--apply", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    report = enrich_identity_embeddings(
        args.db,
        dry_run=not bool(args.apply),
        case_ids=_parse_case_ids(str(args.case_ids)),
        limit=int(args.limit or 0) or None,
        provider_python=args.provider_python,
        worker_script=args.worker_script,
    )
    write_json(args.output, report)
    write_markdown(args.markdown_output, report)
    print(
        json.dumps(
            {"run_status": report["run_status"], "summary": report["summary"], "readiness": report["readiness"]},
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
